#ifndef _CRM_DEFINE_H_
#define _CRM_DEFINE_H_


//////////////////指令字符串//////////
#define OPER_CODE 				"operCode"
#define STAFF_ID				"staffId"
#define DEPART_ID				"departId"
#define PROVINCE_CODE			"provinceCode"
#define REGION_CODE				"regionCode"
#define CITY_CODE				"cityCode"
#define ROUTE_PROVINCE_CODE		"routeProvinceCode"
#define ROUTE_REGION_CODE		"routeRegionCode"
#define ROUTE_CITY_CODE			"routeCityCode"
#define IN_NET_CODE				"inNetMode"
#define TRADE_ID				"tradeId"

#define PARAMETERS				"parameters"

#define TRADE					"trade"
#define ORDER_TYPE				"orderType"
#define SUBSCRIBE_ID			"subscribeId"
#define TRADE_TYPE_CODE			"tradeTypeCode"
#define IN_MODE_CODE			"inModeCode"
#define SUBSCRIBE_STATE			"subscribeState"
#define PACKAGE_ID				"packageId"
#define BRAND_CODE				"brandCode"
#define USER_ID					"userId"
#define CUST_ID					"custId"
#define ACCT_ID					"acctId"
#define NET_TYPE_CODE			"netTypeCode"
#define SERIAL_NUMBER			"serialNumber"
#define CUST_NAME				"custName"
#define FINISH_DATE				"finishDate"
#define ACCEPT_STAFF_ID			"acceptStaffId"
#define ACCEPT_DEPART_ID		"acceptDepartId"
#define ACCEPT_PROVINCE_CODE	"acceptProvinceCode"
#define ACCEPT_REGION_CODE		"acceptReginCode"
#define ACCEPT_CITY_CODE		"acceptCityCode"
#define ACCEPT_DATE				"acceptDate"
#define TERM_IP					"termIp"
#define PROVINCE_CODE			"provinceCode"

#define CITY_CODE				"cityCode"
#define HASE_FEE				"haseFee"
#define FEE_SUM					"feeSum"
#define ACTOR_NAME				"actorName"
#define ACTOR_CERT_TYPE_ID		"actorCerttypeid"
#define ACTOR_PHONE				"actorPhone"
#define ACTOR_CERT_NUM			"actorCertnum"
#define ACCEPT_DATE				"acceptDate"
#define CONTACT					"contact"
#define CONTACT_PHONE			"contactPhone"
#define CONTACT_ADDRESS			"contactAddress"
#define REMARK					"remark"
#define PROVIDER_CODE			"providerCode"

#define RESP_CODE				"respCode"
#define RESP_DESC				"respDesc"

#define RECV_TAG 				"recvTag"
#define RESULT					"result"
#define OWE_FEE_INFO			"oweFeeInfo"
#define LEAVE_REAL_FEE			"leaverealFee"
#define REAL_FEE				"realFee"
#define OWE_FEE					"oweFee"
#define TOTAL_OWE_FEE           "totalOwe"
#define PHONE_NUMBER			"phoneNumber"
#define MSG						"msg"
#define RECV_FEE				"recvFee"
#define PAYMENT_ID				"paymentId"
#define PAYFEE_MODE_CODE		"payFeeModeCode"
#define CHANNEL_ID				"channelId"
#define PAYORDER_NUMBER			"payOrderNumber"
#define PAYCHARGE_ID			"payChargeId"
#define BANK_CODE				"bankCode"
#define CARD_TYPE				"cardType"
#define POST_NUMBER				"postNumber"
#define CHARGE_ID				"chargeId"

#define LAST_MONTH_BILL_FEE     "lastMonthBil"
#define LAST_BILL_PAY_TAG       "payTag"

#define ACTION_CODE             "actionCode"
#define TRADE_TYPE_CODE         "tradeTypeCode"
#define PREPAY_TAG              "prepayTag"


#define TRADE_ITEM              "tradeItem"
#define UPDATE_STAFF_ID         "updateStaffId"
#define UPDATE_DEPART_ID        "updateDepartId"
#define UPDATE_DATE             "updateDate"
#define ITEM_ID                 "itemId"
#define ATTR_CODE               "attrCode"
#define ATTR_VALUE              "attrValue"



#endif

